site:
  title: Capsi Documentaci√≥n
  start_page: ROOT::index.adoc
content:
  sources: 
  - url: .
    branches: HEAD
    start_path: ROOT
ui: 
  bundle:
    url: https://capsi-ucp.github.io/theme-docs/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    page-component-sort-order: ROOT
antora:
  extensions:
  - '@antora/lunr-extension'
